# Generated by Django 4.2.5 on 2023-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
