# Generated by Django 4.2.5 on 2023-09-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='username',
            new_name='uname',
        ),
    ]
